# TensorFlow Machine Learning Project
Juan Arellano - 10/21/2020
https://www.udemy.com/share/103GbhA0UfcF1VR3w=/

In [3]:
#!pip install tensorflow

In [2]:
import tensorflow as tf

In [7]:
print(tf.__version__)

AttributeError: module 'tensorflow' has no attribute '__version__'

Tensors are multi-dimenstional arrays with a uniform data type

In [5]:
# This is a scalar or a rank-0 tensor
print(tf.constant(3))

tf.Tensor(3, shape=(), dtype=int32)


Here, the shape is empty since a scalar does not have any dimensions

In [6]:
# We can assign Tensors to variables
scalar = tf.constant(3)
print(scalar)

tf.Tensor(3, shape=(), dtype=int32)


In [7]:
# we can change data types of a tensor
scalar = tf.constant(3, tf.float64)
print(scalar)

tf.Tensor(3.0, shape=(), dtype=float64)


In [8]:
# The shape of a tensor can be obtained using the shape property
print(scalar.shape)

()


In [9]:
print(scalar.dtype)

<dtype: 'float64'>


In [11]:
# The data help by the Tensor can be obtained using the numpy method
print(scalar.numpy())

3.0


In [13]:
# Creating a 1D tensor
rank_1_tensor = tf.constant([1,2,3], tf.float64)
print(rank_1_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


In [15]:
# Creating a 2D tensor
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]])
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [16]:
rank_3_tensor = tf.constant([
    [[1,2,3],
    [4,5,6]],
    [[7,8,9],
    [10,11,12]]
])

print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


## Different Ways to create Tensors

In [17]:
print(tf.ones([2,2]))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [18]:
print(tf.ones([2,2,2]))

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [19]:
print(tf.zeros([2,2]))

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [20]:
print(tf.eye(3,3))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [21]:
print(tf.fill([2,2], 4))

tf.Tensor(
[[4 4]
 [4 4]], shape=(2, 2), dtype=int32)


In [23]:
# linspace used to create a 1D tensor with even spaced sequence of numbers
print(tf.linspace(0, 9, 5))

tf.Tensor([0.   2.25 4.5  6.75 9.  ], shape=(5,), dtype=float64)


In [25]:
# similarly range method is used to create a 1D tensor with numbers in the range provided
print(tf.range(0, 9, 3))

tf.Tensor([0 3 6], shape=(3,), dtype=int32)


In [26]:
# Can use variable method in order to reassign its values if needed
x = tf.Variable(tf.constant([1,2,3]))
print(x)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [27]:
# We can now assign new tensor values using the assign method
x.assign(tf.constant([4,5,6]))
print(x)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


## Perform Tensor operations in TensorFlow

In [28]:
t1 = tf.constant([10,11,12,13])
t2 = tf.constant([1,2,3,4])

In [29]:
print(tf.add(t1,t2))

tf.Tensor([11 13 15 17], shape=(4,), dtype=int32)


In [30]:
# Same result as above
print(t1 + t2)

tf.Tensor([11 13 15 17], shape=(4,), dtype=int32)


In [31]:
# Must make sure numbers are in order or else output will be different
print(tf.subtract(t1,t2))

tf.Tensor([9 9 9 9], shape=(4,), dtype=int32)


In [32]:
print(t1 - t2)

tf.Tensor([9 9 9 9], shape=(4,), dtype=int32)


In [33]:
print(tf.multiply(t1,t2))

tf.Tensor([10 22 36 52], shape=(4,), dtype=int32)


In [34]:
print(t1 * t2)

tf.Tensor([10 22 36 52], shape=(4,), dtype=int32)


In [35]:
# We can also perform element wise division
t1 = tf.constant([2,4,6,8])
t2 = tf.constant([1,2,3,4])

In [36]:
print(tf.divide(t2, t1))

tf.Tensor([0.5 0.5 0.5 0.5], shape=(4,), dtype=float64)


In [37]:
print(t1 / t2)

tf.Tensor([2. 2. 2. 2.], shape=(4,), dtype=float64)


In [38]:
print(tf.square(t1))

tf.Tensor([ 4 16 36 64], shape=(4,), dtype=int32)


In [39]:
print(tf.square(t2))

tf.Tensor([ 1  4  9 16], shape=(4,), dtype=int32)


In [40]:
# Can also find mean
print(tf.reduce_mean(t1))

tf.Tensor(5, shape=(), dtype=int32)


In [42]:
# Since datatype is being defined as int32 it truncates the .5
print(tf.reduce_mean(t2))

tf.Tensor(2, shape=(), dtype=int32)


In [43]:
# Values of t1 should be added by 5 then subtract values of t1
print(t1 + tf.reduce_mean(t1) - t1)

tf.Tensor([5 5 5 5], shape=(4,), dtype=int32)


## Linear Regression From Scratch in Tensor Flow

Our linear regression model will take in a single feature as an input and output a prediction
- y_hat = wx + b
- y_hat = prediction
- w = weight (or coefficient)
- x = input
- b = bias (or intercept)

The workflow for this project is as follows:

- Prepare the data
- Randomly initialize the weights and bias
- Build the model architecture
- Iteratively update the weights and train the model using gradient descent

Our dataset for this project will be self-made. Two variables x,y consisting of 6 datapoints each.

In [44]:
import random

In [45]:
# Let us define x, y variables
x = tf.constant([1,2,3,4,5,6], tf.float32)
y = tf.constant([100,200,300,400,500,600], tf.float32)

In [46]:
# Using variables we will be able to reassign these values later on
# Weight (w)
w = tf.Variable(tf.constant(random.uniform(0,1)))

# Bias (b)
b = tf.Variable(tf.constant(random.uniform(0,1)))

print(w)
print(b)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.794205>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.70480055>


In [47]:
# Now we will create a function called predict() which will compute y_hat = wx + b
def predict(X, w, b):
    y_hat = tf.multiply(w, x) + b
    return y_hat

In [48]:
# Now we can make from our model without training it
prediction = predict(x, w, b)
print(prediction)

tf.Tensor([1.4990056 2.2932105 3.0874157 3.8816206 4.6758256 5.470031 ], shape=(6,), dtype=float32)


In [49]:
# To train our model we will be using the Mean Squared Error as our loss function
def loss(y_hat, y):
    squared_error = tf.square(y_hat - y)
    mse = tf.reduce_mean(squared_error)
    return mse

In [50]:
print(loss(prediction, y))

tf.Tensor(148778.2, shape=(), dtype=float32)


In [51]:
def train(x, y, w, b):
    
    # Define the learning rate
    learning_rate = 0.05
    
    with tf.GradientTape() as t:
        
        # Get prediction
        y_hat = predict(x, w, b)
        # Compute the loss
        step_loss = loss(y_hat, y)
       
    # Find the gradient
    grad_w, grad_b = t.gradient(step_loss, [w,b])
    
    # Update weight
    w.assign_sub(learning_rate * grad_w)
    
    # Update bias
    b.assign_sub(learning_rate * grad_b)

In [52]:
# Initialize the model
for epoch in range(2000):
    
    # Train the model
    train(x, y, w, b)

In [53]:
prediction = predict(x, w, b)
print(prediction)

tf.Tensor([100.00003 200.00003 300.00006 400.00006 500.00006 600.00006], shape=(6,), dtype=float32)


In [54]:
print(loss(prediction, y))

tf.Tensor(2.7939677e-09, shape=(), dtype=float32)


## Linear Regression Using a Sequential Model
Our linear regression model will be made using a sequential model consisting of a dense layer with 1 neuron. The neuron will take in an input and output a prediction by calculating y_hat = wx + b. The workflow is as follows:
- Prepare the data
- Build the model architecture in TensorFlow.js
- Train the model using Stochastic Gradient Descent as out optimizer and Mean Squared Error as our loss function

Our dataset will be self-made. Our goal is to build and train a linear regression model to predict y using x.

In [55]:
# Let us define x, y variables
x = tf.constant([1,2,3,4,5,6], tf.float32)
y = tf.constant([100,200,300,400,500,600], tf.float32)

In [58]:
# We can create a model architecture by using the Sequential model from Keras
linear_model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 1, input_shape = (1, ), use_bias = 'True')
])

In [59]:
linear_model.predict(x)

array([[1.2928234],
       [2.5856469],
       [3.8784704],
       [5.1712937],
       [6.464117 ],
       [7.756941 ]], dtype=float32)

In [60]:
# Now we can train the model
linear_model.compile(
    optimizer = tf.optimizers.SGD(learning_rate = 0.05),
    loss = 'mean_squared_error')

In [61]:
linear_model.fit(x, y, epochs = 2000)

Epoch 1/2000
1/1 [==============================] - 0s 856us/step - loss: 147770.4531
Epoch 2/2000
1/1 [==============================] - 0s 521us/step - loss: 52973.1680
Epoch 3/2000
1/1 [==============================] - 0s 498us/step - loss: 19023.6914
Epoch 4/2000
1/1 [==============================] - 0s 550us/step - loss: 6864.2544
Epoch 5/2000
1/1 [==============================] - 0s 562us/step - loss: 2508.0173
Epoch 6/2000
1/1 [==============================] - 0s 463us/step - loss: 946.2188
Epoch 7/2000
1/1 [==============================] - 0s 454us/step - loss: 385.1908
Epoch 8/2000
1/1 [==============================] - 0s 509us/step - loss: 182.6071
Epoch 9/2000
1/1 [==============================] - 0s 650us/step - loss: 108.4458
Epoch 10/2000
1/1 [==============================] - 0s 486us/step - loss: 80.3312
Epoch 11/2000
1/1 [==============================] - 0s 559us/step - loss: 68.7624
Epoch 12/2000
1/1 [==============================] - 0s 552us/step - loss: 63.

1/1 [==============================] - 0s 2ms/step - loss: 0.0649
Epoch 199/2000
1/1 [==============================] - 0s 867us/step - loss: 0.0626
Epoch 200/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.0603
Epoch 201/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.0581
Epoch 202/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.0560
Epoch 203/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.0540
Epoch 204/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.0521
Epoch 205/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.0502
Epoch 206/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.0484
Epoch 207/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.0466
Epoch 208/2000
1/1 [==============================] - 0s 682us/step - loss: 0.0449
Epoch 209/2000
1/1 [==============================] - 0s 707us/step - loss: 0.0433
Epoch 210/2000
1/1 [=================

1/1 [==============================] - 0s 756us/step - loss: 5.1231e-05
Epoch 393/2000
1/1 [==============================] - 0s 623us/step - loss: 4.9421e-05
Epoch 394/2000
1/1 [==============================] - 0s 971us/step - loss: 4.7552e-05
Epoch 395/2000
1/1 [==============================] - 0s 614us/step - loss: 4.5870e-05
Epoch 396/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.4255e-05
Epoch 397/2000
1/1 [==============================] - 0s 925us/step - loss: 4.2580e-05
Epoch 398/2000
1/1 [==============================] - 0s 691us/step - loss: 4.1115e-05
Epoch 399/2000
1/1 [==============================] - 0s 1ms/step - loss: 3.9575e-05
Epoch 400/2000
1/1 [==============================] - 0s 1ms/step - loss: 3.8113e-05
Epoch 401/2000
1/1 [==============================] - 0s 1ms/step - loss: 3.6818e-05
Epoch 402/2000
1/1 [==============================] - 0s 870us/step - loss: 3.5463e-05
Epoch 403/2000
1/1 [==============================] - 0s 733us/ste

1/1 [==============================] - 0s 983us/step - loss: 5.3716e-08
Epoch 581/2000
1/1 [==============================] - 0s 679us/step - loss: 4.9554e-08
Epoch 582/2000
1/1 [==============================] - 0s 841us/step - loss: 4.7187e-08
Epoch 583/2000
1/1 [==============================] - 0s 736us/step - loss: 4.5179e-08
Epoch 584/2000
1/1 [==============================] - 0s 842us/step - loss: 4.1919e-08
Epoch 585/2000
1/1 [==============================] - 0s 631us/step - loss: 3.9280e-08
Epoch 586/2000
1/1 [==============================] - 0s 591us/step - loss: 4.3277e-08
Epoch 587/2000
1/1 [==============================] - 0s 568us/step - loss: 4.0707e-08
Epoch 588/2000
1/1 [==============================] - 0s 724us/step - loss: 3.8068e-08
Epoch 589/2000
1/1 [==============================] - 0s 609us/step - loss: 3.6360e-08
Epoch 590/2000
1/1 [==============================] - 0s 1ms/step - loss: 3.5516e-08
Epoch 591/2000
1/1 [==============================] - 0s 855

1/1 [==============================] - 0s 1ms/step - loss: 2.1052e-09
Epoch 676/2000
1/1 [==============================] - 0s 950us/step - loss: 1.9015e-09
Epoch 677/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.9015e-09
Epoch 678/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.6298e-09
Epoch 679/2000
1/1 [==============================] - 0s 946us/step - loss: 1.4455e-09
Epoch 680/2000
1/1 [==============================] - 0s 707us/step - loss: 1.4455e-09
Epoch 681/2000
1/1 [==============================] - 0s 931us/step - loss: 2.0664e-09
Epoch 682/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.6776e-09
Epoch 683/2000
1/1 [==============================] - 0s 737us/step - loss: 2.4932e-09
Epoch 684/2000
1/1 [==============================] - 0s 783us/step - loss: 2.4932e-09
Epoch 685/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.2216e-09
Epoch 686/2000
1/1 [==============================] - 0s 4ms/step - 

1/1 [==============================] - 0s 850us/step - loss: 2.9880e-09
Epoch 864/2000
1/1 [==============================] - 0s 630us/step - loss: 5.9178e-10
Epoch 865/2000
1/1 [==============================] - 0s 769us/step - loss: 6.3058e-10
Epoch 866/2000
1/1 [==============================] - 0s 650us/step - loss: 5.4327e-10
Epoch 867/2000
1/1 [==============================] - 0s 753us/step - loss: 6.3058e-10
Epoch 868/2000
1/1 [==============================] - 0s 674us/step - loss: 5.4327e-10
Epoch 869/2000
1/1 [==============================] - 0s 956us/step - loss: 1.0962e-09
Epoch 870/2000
1/1 [==============================] - 0s 759us/step - loss: 2.7261e-09
Epoch 871/2000
1/1 [==============================] - 0s 804us/step - loss: 4.3850e-09
Epoch 872/2000
1/1 [==============================] - 0s 589us/step - loss: 2.7261e-09
Epoch 873/2000
1/1 [==============================] - 0s 642us/step - loss: 4.3850e-09
Epoch 874/2000
1/1 [==============================] - 0s 7

Epoch 1051/2000
1/1 [==============================] - 0s 671us/step - loss: 4.3850e-09
Epoch 1052/2000
1/1 [==============================] - 0s 591us/step - loss: 2.7940e-09
Epoch 1053/2000
1/1 [==============================] - 0s 862us/step - loss: 4.3850e-09
Epoch 1054/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.7940e-09
Epoch 1055/2000
1/1 [==============================] - 0s 691us/step - loss: 4.3850e-09
Epoch 1056/2000
1/1 [==============================] - 0s 647us/step - loss: 2.7940e-09
Epoch 1057/2000
1/1 [==============================] - 0s 651us/step - loss: 4.3850e-09
Epoch 1058/2000
1/1 [==============================] - 0s 819us/step - loss: 2.7940e-09
Epoch 1059/2000
1/1 [==============================] - 0s 749us/step - loss: 2.9880e-09
Epoch 1060/2000
1/1 [==============================] - 0s 945us/step - loss: 5.9178e-10
Epoch 1061/2000
1/1 [==============================] - 0s 733us/step - loss: 6.3058e-10
Epoch 1062/2000
1/1 [=============

1/1 [==============================] - 0s 712us/step - loss: 4.3850e-09
Epoch 1238/2000
1/1 [==============================] - 0s 677us/step - loss: 2.7261e-09
Epoch 1239/2000
1/1 [==============================] - 0s 654us/step - loss: 4.3850e-09
Epoch 1240/2000
1/1 [==============================] - 0s 672us/step - loss: 2.7261e-09
Epoch 1241/2000
1/1 [==============================] - 0s 852us/step - loss: 4.3850e-09
Epoch 1242/2000
1/1 [==============================] - 0s 748us/step - loss: 2.7261e-09
Epoch 1243/2000
1/1 [==============================] - 0s 630us/step - loss: 4.3850e-09
Epoch 1244/2000
1/1 [==============================] - 0s 638us/step - loss: 2.7261e-09
Epoch 1245/2000
1/1 [==============================] - 0s 803us/step - loss: 4.3850e-09
Epoch 1246/2000
1/1 [==============================] - 0s 689us/step - loss: 2.7940e-09
Epoch 1247/2000
1/1 [==============================] - 0s 599us/step - loss: 4.3850e-09
Epoch 1248/2000
1/1 [===========================

Epoch 1331/2000
1/1 [==============================] - 0s 687us/step - loss: 4.3850e-09
Epoch 1332/2000
1/1 [==============================] - 0s 629us/step - loss: 2.7940e-09
Epoch 1333/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.3850e-09
Epoch 1334/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.7940e-09
Epoch 1335/2000
1/1 [==============================] - 0s 744us/step - loss: 4.3850e-09
Epoch 1336/2000
1/1 [==============================] - 0s 727us/step - loss: 2.7940e-09
Epoch 1337/2000
1/1 [==============================] - 0s 616us/step - loss: 4.3850e-09
Epoch 1338/2000
1/1 [==============================] - 0s 682us/step - loss: 2.7940e-09
Epoch 1339/2000
1/1 [==============================] - 0s 769us/step - loss: 2.9880e-09
Epoch 1340/2000
1/1 [==============================] - 0s 603us/step - loss: 5.9178e-10
Epoch 1341/2000
1/1 [==============================] - 0s 695us/step - loss: 6.3058e-10
Epoch 1342/2000
1/1 [===============

Epoch 1424/2000
1/1 [==============================] - 0s 1ms/step - loss: 5.9178e-10
Epoch 1425/2000
1/1 [==============================] - 0s 1ms/step - loss: 6.3058e-10
Epoch 1426/2000
1/1 [==============================] - 0s 665us/step - loss: 5.4327e-10
Epoch 1427/2000
1/1 [==============================] - 0s 589us/step - loss: 6.3058e-10
Epoch 1428/2000
1/1 [==============================] - 0s 1ms/step - loss: 5.4327e-10
Epoch 1429/2000
1/1 [==============================] - 0s 804us/step - loss: 1.0962e-09
Epoch 1430/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.7261e-09
Epoch 1431/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.3850e-09
Epoch 1432/2000
1/1 [==============================] - 0s 971us/step - loss: 2.7261e-09
Epoch 1433/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.3850e-09
Epoch 1434/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.7261e-09
Epoch 1435/2000
1/1 [=========================

1/1 [==============================] - 0s 740us/step - loss: 2.7940e-09
Epoch 1611/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.3850e-09
Epoch 1612/2000
1/1 [==============================] - 0s 782us/step - loss: 2.7940e-09
Epoch 1613/2000
1/1 [==============================] - 0s 772us/step - loss: 4.3850e-09
Epoch 1614/2000
1/1 [==============================] - 0s 677us/step - loss: 2.7940e-09
Epoch 1615/2000
1/1 [==============================] - 0s 662us/step - loss: 4.3850e-09
Epoch 1616/2000
1/1 [==============================] - 0s 958us/step - loss: 2.7940e-09
Epoch 1617/2000
1/1 [==============================] - 0s 718us/step - loss: 4.3850e-09
Epoch 1618/2000
1/1 [==============================] - 0s 653us/step - loss: 2.7940e-09
Epoch 1619/2000
1/1 [==============================] - 0s 689us/step - loss: 2.9880e-09
Epoch 1620/2000
1/1 [==============================] - 0s 969us/step - loss: 5.9178e-10
Epoch 1621/2000
1/1 [=============================

Epoch 1704/2000
1/1 [==============================] - 0s 1ms/step - loss: 5.9178e-10
Epoch 1705/2000
1/1 [==============================] - 0s 1ms/step - loss: 6.3058e-10
Epoch 1706/2000
1/1 [==============================] - 0s 1ms/step - loss: 5.4327e-10
Epoch 1707/2000
1/1 [==============================] - 0s 821us/step - loss: 6.3058e-10
Epoch 1708/2000
1/1 [==============================] - 0s 2ms/step - loss: 5.4327e-10
Epoch 1709/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.0962e-09
Epoch 1710/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.7261e-09
Epoch 1711/2000
1/1 [==============================] - 0s 895us/step - loss: 4.3850e-09
Epoch 1712/2000
1/1 [==============================] - 0s 910us/step - loss: 2.7261e-09
Epoch 1713/2000
1/1 [==============================] - 0s 730us/step - loss: 4.3850e-09
Epoch 1714/2000
1/1 [==============================] - 0s 894us/step - loss: 2.7261e-09
Epoch 1715/2000
1/1 [=======================

1/1 [==============================] - 0s 651us/step - loss: 4.3850e-09
Epoch 1892/2000
1/1 [==============================] - 0s 689us/step - loss: 2.7940e-09
Epoch 1893/2000
1/1 [==============================] - 0s 735us/step - loss: 4.3850e-09
Epoch 1894/2000
1/1 [==============================] - 0s 691us/step - loss: 2.7940e-09
Epoch 1895/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.3850e-09
Epoch 1896/2000
1/1 [==============================] - 0s 822us/step - loss: 2.7940e-09
Epoch 1897/2000
1/1 [==============================] - 0s 740us/step - loss: 4.3850e-09
Epoch 1898/2000
1/1 [==============================] - 0s 600us/step - loss: 2.7940e-09
Epoch 1899/2000
1/1 [==============================] - 0s 658us/step - loss: 2.9880e-09
Epoch 1900/2000
1/1 [==============================] - 0s 800us/step - loss: 5.9178e-10
Epoch 1901/2000
1/1 [==============================] - 0s 882us/step - loss: 6.3058e-10
Epoch 1902/2000
1/1 [=============================

In [62]:
linear_model.predict(x)

array([[100.     ],
       [199.99998],
       [299.99994],
       [399.99994],
       [499.99994],
       [599.9999 ]], dtype=float32)

## Logistic Regression Using a Sequential Model
Our linear regression model will be made using a sequential model consisting of a dense layer with 1 neuron. The neuron will take in an input and output a prediction by calculating y_hat = sigmoid(wx + b). The sigmoid activation function gives the probability of the output class between 0 and 1. The workflow is as follows:
- Prepare the data
- Build the model architecture in TensorFlow.js
- Train the model using Stochastic Gradient Descent as out optimizer and Binary Cross Entropy as our loss function

Our dataset will be self-made. Our goal is to build and train a logistic regression model to predict y using x.

In [6]:
# Let us define x, y variables
x = tf.constant([1,2,3,4,5,6], tf.float32)
y = tf.constant([0,0,0,1,1,1], tf.float32)

AttributeError: module 'tensorflow' has no attribute 'constant'

In [66]:
# let us create our model architecture by using Sequential model from Keras
logistic_model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 1, input_shape = (1, ), use_bias = 'True', activation = 'sigmoid')
])

In [67]:
# Let us make some predictions using the model
print(logistic_model.predict(x))

[[1.8763873e-01]
 [5.0649256e-02]
 [1.2173116e-02]
 [2.8383136e-03]
 [6.5702200e-04]
 [1.5181303e-04]]


In [68]:
# To train the model, we will be using the loss as Binary Cross Entropy and the optimizer as
# Stochastic Gradient Descent
logistic_model.compile(
    optimizer = tf.optimizers.SGD(learning_rate = 0.05),
    loss= 'binary_crossentropy')

In [69]:
# Train the model by calling the fit method
logistic_model.fit(x, y, epochs = 2000)

Epoch 1/2000
1/1 [==============================] - 0s 1ms/step - loss: 3.7095
Epoch 2/2000
1/1 [==============================] - 0s 465us/step - loss: 3.4015
Epoch 3/2000
1/1 [==============================] - 0s 517us/step - loss: 3.0973
Epoch 4/2000
1/1 [==============================] - 0s 442us/step - loss: 2.7981
Epoch 5/2000
1/1 [==============================] - 0s 566us/step - loss: 2.5056
Epoch 6/2000
1/1 [==============================] - 0s 529us/step - loss: 2.2221
Epoch 7/2000
1/1 [==============================] - 0s 431us/step - loss: 1.9505
Epoch 8/2000
1/1 [==============================] - 0s 430us/step - loss: 1.6953
Epoch 9/2000
1/1 [==============================] - 0s 435us/step - loss: 1.4620
Epoch 10/2000
1/1 [==============================] - 0s 460us/step - loss: 1.2570
Epoch 11/2000
1/1 [==============================] - 0s 577us/step - loss: 1.0862
Epoch 12/2000
1/1 [==============================] - 0s 553us/step - loss: 0.9528
Epoch 13/2000
1/1 [========

1/1 [==============================] - 0s 921us/step - loss: 0.5446
Epoch 102/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5434
Epoch 103/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5423
Epoch 104/2000
1/1 [==============================] - 0s 986us/step - loss: 0.5411
Epoch 105/2000
1/1 [==============================] - 0s 780us/step - loss: 0.5400
Epoch 106/2000
1/1 [==============================] - 0s 708us/step - loss: 0.5389
Epoch 107/2000
1/1 [==============================] - 0s 578us/step - loss: 0.5377
Epoch 108/2000
1/1 [==============================] - 0s 629us/step - loss: 0.5366
Epoch 109/2000
1/1 [==============================] - 0s 657us/step - loss: 0.5355
Epoch 110/2000
1/1 [==============================] - 0s 760us/step - loss: 0.5344
Epoch 111/2000
1/1 [==============================] - 0s 854us/step - loss: 0.5333
Epoch 112/2000
1/1 [==============================] - 0s 826us/step - loss: 0.5322
Epoch 113/2000
1/1 [===

1/1 [==============================] - 0s 945us/step - loss: 0.4506
Epoch 201/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4498
Epoch 202/2000
1/1 [==============================] - 0s 732us/step - loss: 0.4490
Epoch 203/2000
1/1 [==============================] - 0s 564us/step - loss: 0.4483
Epoch 204/2000
1/1 [==============================] - 0s 635us/step - loss: 0.4475
Epoch 205/2000
1/1 [==============================] - 0s 557us/step - loss: 0.4467
Epoch 206/2000
1/1 [==============================] - 0s 668us/step - loss: 0.4460
Epoch 207/2000
1/1 [==============================] - 0s 889us/step - loss: 0.4452
Epoch 208/2000
1/1 [==============================] - 0s 699us/step - loss: 0.4445
Epoch 209/2000
1/1 [==============================] - 0s 815us/step - loss: 0.4437
Epoch 210/2000
1/1 [==============================] - 0s 597us/step - loss: 0.4430
Epoch 211/2000
1/1 [==============================] - 0s 740us/step - loss: 0.4422
Epoch 212/2000
1/1 [=

1/1 [==============================] - 0s 633us/step - loss: 0.3411
Epoch 399/2000
1/1 [==============================] - 0s 605us/step - loss: 0.3407
Epoch 400/2000
1/1 [==============================] - 0s 708us/step - loss: 0.3403
Epoch 401/2000
1/1 [==============================] - 0s 810us/step - loss: 0.3399
Epoch 402/2000
1/1 [==============================] - 0s 623us/step - loss: 0.3395
Epoch 403/2000
1/1 [==============================] - 0s 694us/step - loss: 0.3391
Epoch 404/2000
1/1 [==============================] - 0s 791us/step - loss: 0.3387
Epoch 405/2000
1/1 [==============================] - 0s 905us/step - loss: 0.3384
Epoch 406/2000
1/1 [==============================] - 0s 764us/step - loss: 0.3380
Epoch 407/2000
1/1 [==============================] - 0s 962us/step - loss: 0.3376
Epoch 408/2000
1/1 [==============================] - 0s 754us/step - loss: 0.3372
Epoch 409/2000
1/1 [==============================] - 0s 679us/step - loss: 0.3368
Epoch 410/2000
1/1 

1/1 [==============================] - 0s 816us/step - loss: 0.3073
Epoch 498/2000
1/1 [==============================] - 0s 732us/step - loss: 0.3071
Epoch 499/2000
1/1 [==============================] - 0s 637us/step - loss: 0.3068
Epoch 500/2000
1/1 [==============================] - 0s 592us/step - loss: 0.3065
Epoch 501/2000
1/1 [==============================] - 0s 700us/step - loss: 0.3062
Epoch 502/2000
1/1 [==============================] - 0s 932us/step - loss: 0.3059
Epoch 503/2000
1/1 [==============================] - 0s 863us/step - loss: 0.3056
Epoch 504/2000
1/1 [==============================] - 0s 722us/step - loss: 0.3053
Epoch 505/2000
1/1 [==============================] - 0s 620us/step - loss: 0.3050
Epoch 506/2000
1/1 [==============================] - 0s 676us/step - loss: 0.3047
Epoch 507/2000
1/1 [==============================] - 0s 689us/step - loss: 0.3044
Epoch 508/2000
1/1 [==============================] - 0s 897us/step - loss: 0.3041
Epoch 509/2000
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 0.2608
Epoch 696/2000
1/1 [==============================] - 0s 677us/step - loss: 0.2606
Epoch 697/2000
1/1 [==============================] - 0s 680us/step - loss: 0.2604
Epoch 698/2000
1/1 [==============================] - 0s 703us/step - loss: 0.2602
Epoch 699/2000
1/1 [==============================] - 0s 880us/step - loss: 0.2600
Epoch 700/2000
1/1 [==============================] - 0s 791us/step - loss: 0.2598
Epoch 701/2000
1/1 [==============================] - 0s 712us/step - loss: 0.2597
Epoch 702/2000
1/1 [==============================] - 0s 626us/step - loss: 0.2595
Epoch 703/2000
1/1 [==============================] - 0s 774us/step - loss: 0.2593
Epoch 704/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2591
Epoch 705/2000
1/1 [==============================] - 0s 919us/step - loss: 0.2589
Epoch 706/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2587
Epoch 707/2000
1/1 [=====

Epoch 893/2000
1/1 [==============================] - 0s 772us/step - loss: 0.2300
Epoch 894/2000
1/1 [==============================] - 0s 856us/step - loss: 0.2298
Epoch 895/2000
1/1 [==============================] - 0s 567us/step - loss: 0.2297
Epoch 896/2000
1/1 [==============================] - 0s 635us/step - loss: 0.2296
Epoch 897/2000
1/1 [==============================] - 0s 770us/step - loss: 0.2294
Epoch 898/2000
1/1 [==============================] - 0s 626us/step - loss: 0.2293
Epoch 899/2000
1/1 [==============================] - 0s 767us/step - loss: 0.2292
Epoch 900/2000
1/1 [==============================] - 0s 700us/step - loss: 0.2291
Epoch 901/2000
1/1 [==============================] - 0s 740us/step - loss: 0.2289
Epoch 902/2000
1/1 [==============================] - 0s 787us/step - loss: 0.2288
Epoch 903/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2287
Epoch 904/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2285
Epoch 90

1/1 [==============================] - 0s 830us/step - loss: 0.2081
Epoch 1090/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2080
Epoch 1091/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2079
Epoch 1092/2000
1/1 [==============================] - 0s 727us/step - loss: 0.2078
Epoch 1093/2000
1/1 [==============================] - 0s 683us/step - loss: 0.2077
Epoch 1094/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2076
Epoch 1095/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2075
Epoch 1096/2000
1/1 [==============================] - 0s 682us/step - loss: 0.2074
Epoch 1097/2000
1/1 [==============================] - 0s 601us/step - loss: 0.2073
Epoch 1098/2000
1/1 [==============================] - 0s 975us/step - loss: 0.2072
Epoch 1099/2000
1/1 [==============================] - 0s 857us/step - loss: 0.2071
Epoch 1100/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2070
Epoch 1101/2000
1/

1/1 [==============================] - 0s 610us/step - loss: 0.1914
Epoch 1286/2000
1/1 [==============================] - 0s 770us/step - loss: 0.1913
Epoch 1287/2000
1/1 [==============================] - 0s 754us/step - loss: 0.1913
Epoch 1288/2000
1/1 [==============================] - 0s 734us/step - loss: 0.1912
Epoch 1289/2000
1/1 [==============================] - 0s 623us/step - loss: 0.1911
Epoch 1290/2000
1/1 [==============================] - 0s 662us/step - loss: 0.1910
Epoch 1291/2000
1/1 [==============================] - 0s 628us/step - loss: 0.1910
Epoch 1292/2000
1/1 [==============================] - 0s 688us/step - loss: 0.1909
Epoch 1293/2000
1/1 [==============================] - 0s 840us/step - loss: 0.1908
Epoch 1294/2000
1/1 [==============================] - 0s 840us/step - loss: 0.1907
Epoch 1295/2000
1/1 [==============================] - 0s 898us/step - loss: 0.1907
Epoch 1296/2000
1/1 [==============================] - 0s 903us/step - loss: 0.1906
Epoch 12

1/1 [==============================] - 0s 645us/step - loss: 0.1782
Epoch 1482/2000
1/1 [==============================] - 0s 815us/step - loss: 0.1781
Epoch 1483/2000
1/1 [==============================] - 0s 730us/step - loss: 0.1781
Epoch 1484/2000
1/1 [==============================] - 0s 673us/step - loss: 0.1780
Epoch 1485/2000
1/1 [==============================] - 0s 809us/step - loss: 0.1780
Epoch 1486/2000
1/1 [==============================] - 0s 684us/step - loss: 0.1779
Epoch 1487/2000
1/1 [==============================] - 0s 570us/step - loss: 0.1778
Epoch 1488/2000
1/1 [==============================] - 0s 735us/step - loss: 0.1778
Epoch 1489/2000
1/1 [==============================] - 0s 821us/step - loss: 0.1777
Epoch 1490/2000
1/1 [==============================] - 0s 952us/step - loss: 0.1777
Epoch 1491/2000
1/1 [==============================] - 0s 737us/step - loss: 0.1776
Epoch 1492/2000
1/1 [==============================] - 0s 707us/step - loss: 0.1775
Epoch 14

Epoch 1676/2000
1/1 [==============================] - 0s 652us/step - loss: 0.1675
Epoch 1677/2000
1/1 [==============================] - 0s 596us/step - loss: 0.1674
Epoch 1678/2000
1/1 [==============================] - 0s 780us/step - loss: 0.1674
Epoch 1679/2000
1/1 [==============================] - 0s 884us/step - loss: 0.1673
Epoch 1680/2000
1/1 [==============================] - 0s 646us/step - loss: 0.1673
Epoch 1681/2000
1/1 [==============================] - 0s 790us/step - loss: 0.1672
Epoch 1682/2000
1/1 [==============================] - 0s 673us/step - loss: 0.1672
Epoch 1683/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1671
Epoch 1684/2000
1/1 [==============================] - ETA: 0s - loss: 0.167 - 0s 1ms/step - loss: 0.1671
Epoch 1685/2000
1/1 [==============================] - 0s 962us/step - loss: 0.1670
Epoch 1686/2000
1/1 [==============================] - 0s 673us/step - loss: 0.1670
Epoch 1687/2000
1/1 [==============================] - 0

1/1 [==============================] - 0s 679us/step - loss: 0.1584
Epoch 1872/2000
1/1 [==============================] - 0s 624us/step - loss: 0.1584
Epoch 1873/2000
1/1 [==============================] - 0s 805us/step - loss: 0.1584
Epoch 1874/2000
1/1 [==============================] - 0s 884us/step - loss: 0.1583
Epoch 1875/2000
1/1 [==============================] - 0s 617us/step - loss: 0.1583
Epoch 1876/2000
1/1 [==============================] - 0s 679us/step - loss: 0.1582
Epoch 1877/2000
1/1 [==============================] - 0s 844us/step - loss: 0.1582
Epoch 1878/2000
1/1 [==============================] - 0s 653us/step - loss: 0.1581
Epoch 1879/2000
1/1 [==============================] - 0s 709us/step - loss: 0.1581
Epoch 1880/2000
1/1 [==============================] - 0s 793us/step - loss: 0.1581
Epoch 1881/2000
1/1 [==============================] - 0s 704us/step - loss: 0.1580
Epoch 1882/2000
1/1 [==============================] - 0s 740us/step - loss: 0.1580
Epoch 18

1/1 [==============================] - 0s 557us/step - loss: 0.1544
Epoch 1970/2000
1/1 [==============================] - 0s 654us/step - loss: 0.1544
Epoch 1971/2000
1/1 [==============================] - 0s 945us/step - loss: 0.1543
Epoch 1972/2000
1/1 [==============================] - 0s 593us/step - loss: 0.1543
Epoch 1973/2000
1/1 [==============================] - 0s 737us/step - loss: 0.1543
Epoch 1974/2000
1/1 [==============================] - 0s 834us/step - loss: 0.1542
Epoch 1975/2000
1/1 [==============================] - 0s 652us/step - loss: 0.1542
Epoch 1976/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1542
Epoch 1977/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1541
Epoch 1978/2000
1/1 [==============================] - 0s 923us/step - loss: 0.1541
Epoch 1979/2000
1/1 [==============================] - 0s 724us/step - loss: 0.1540
Epoch 1980/2000
1/1 [==============================] - 0s 859us/step - loss: 0.1540
Epoch 1981/2

In [70]:
print(logistic_model.predict(x))

[[0.01893494]
 [0.09458435]
 [0.36119634]
 [0.75371987]
 [0.9430679 ]
 [0.9889696 ]]


## Deep Neural Network Classifier

In [10]:
# Let us define x, y variables
import tensorflow as tf

In [11]:
x = tf.constant([1,2,3,4,5,6], tf.float32)
y = tf.constant([100,200,300,400,500,600], tf.float32)

AttributeError: module 'tensorflow' has no attribute 'constant'

In [ ]:
# Again we will create our model architecture by using the Sequential model from Keras
classifier_model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 20, input_shape = (1, )),
    tf.keras.layers.Dense(units = 20),
    tf.keras.layers.Dense(units = 1, use_bias = 'True', activation = 'sigmoid')
])

In [ ]:
print(classifier_model.predict(x))

In [ ]:
# We can use Binary Cross Entropy for loss and optimizer as Stochastic Gradient Descent
classifier_model.compile(
    optimizer = tf.optimizers.SGD(learning_rate = 0.05),
    loss = 'binary_crossentropy')

In [ ]:
# Now we can train the model by calling the fit method 
classifier_model.fit(x, y, epochs = 2000)

In [ ]:
classifier_model.predict(x)